alias sz="source ~/.zshrc"
alias ez="$EDITOR ~/.zshrc"
alias eg="$EDITOR ~/.gitconfig"
alias eb="$EDITOR ~/.bash_profile"
alias ec="$EDITOR ~/.oh-my-zsh/custom"
alias en="$EDITOR ~/.oh-my-zsh/custom/navi"
alias es="$EDITOR ~/.oh-my-zsh/custom/shorthands.zsh"
alias ee="$EDITOR ~/.oh-my-zsh/custom/editor.zsh"
