export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# Docker completion configuration
# Ensure docker completion is properly set up
zstyle ':omz:plugins:docker' completions false

plugins=(
    alias-finder
    aliases
    brew
    docker-compose
    git
    gitignore
    nvm
    pip
    podman
    python
    uv
    z
    zsh-autosuggestions
)

zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes   # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes    # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes  # disabled by default

source $ZSH/oh-my-zsh.sh

unalias grep 2>/dev/null
export PATH="$HOME/.local/bin:$PATH"
